version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=dev_store
      - DB_USER=devuser
      - DB_PASS=qwerty
    depends_on:
      - db



  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dev_store
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=qwerty


volumes:
  dev-db-data:

